# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Holophenotype5HT',
                'doc_host': 'https://sangyu.github.io',
                'git_url': 'https://github.com/sangyu/Holophenotype5HT',
                'lib_path': 'Holophenotype5HT'},
  'syms': { 'Holophenotype5HT.core': {},
            'Holophenotype5HT.preprocessing': { 'Holophenotype5HT.preprocessing.preprocessData': ( '00_Preprocessing/behavior '
                                                                                                   'preprocessing.html#preprocessdata',
                                                                                                   'Holophenotype5HT/preprocessing.py')}}}
