# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Holophenotype5HT',
                'doc_host': 'https://sangyu.github.io',
                'git_url': 'https://github.com/sangyu/Holophenotype5HT',
                'lib_path': 'Holophenotype5HT'},
  'syms': {'Holophenotype5HT.core': {'Holophenotype5HT.core.foo': ('core.html#foo', 'Holophenotype5HT/core.py')}}}
